# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item',
            new_name='items',
        ),
    ]
