# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160326_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userRole',
            field=models.CharField(choices=[('V', 'Vendor'), ('S', 'Supervisor'), ('B', 'Buyer')], default='B', max_length=1),
        ),
    ]
