# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160327_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.AddField(
            model_name='inventory',
            name='bike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='scooty',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
