# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160327_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Inventory'),
        ),
    ]
