# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160327_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='bike',
        ),
    ]
