# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_inventory_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bike',
            field=models.IntegerField(default=0),
        ),
    ]
